# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Welcome to the Pacific Visualization 2024
email: "to be announced"
description: >- # this means to ignore newlines until "baseurl:"
  PacificVis 2024 will be held in the spring of 2024 at Tokyo, Japan.
author: publicity
baseurl: "/pvis2024" # the subpath of your site, e.g. /blog
url: "https://pvis2024.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: PacivicVis
facebook_username: PacificVis
github_username:  jekyll

# Build settings
#theme: minima
#theme: jekyll-theme-so-simple
theme: minimal-mistakes-jekyll
#remote_theme: coogie/oscailte
#theme: oscailte
plugins:
  - jekyll-feed

sass:
  quiet_deps: true

atom_feed:
  hide: true

defaults:
  - scope:
      path: "pages/cfp/*.md"
    values:
      sidebar:
        nav: "contribute"
  - scope:
      path: "pages/attend/*.md"
    values:
      sidebar:
        nav: "attend"
  - scope:
      path: "pages/papers/*.md"
    values:
      sidebar:
        nav: "accepted"
  - scope:
      path: "pages"
      type: "pages"
    values:
      header:
        image: /assets/images/teaser_pvis2024.png
        image_description: "IEEE 17th Pacific Visualization Symposium (PacificVis 2024) will be held from April 23 through April 26, 2024 at Mita campus, Keio University, Tokyo, Japan."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - .nojekyll

exclude:
  - bin/
  - etc/
  - Readme.md
  - theme
  - work
